### ISSUE TITLE
When open Order Detail window , Order doesn't automatically show.

### ISSUE THREAD

**Issue by narongchaip** [tggwlcube/CuBe_NTS#10]
Previously, when open order detail window , all order will show. 
but now, must select date and click show button. (default from date is 27Mar to 27April)
Operator want to order detail window automatically show and from date use current date.

![cube_nts_issue_04022015_01_1](https://cloud.githubusercontent.com/assets/9858029/6035169/d22a2b62-ac60-11e4-9f15-61baf002c442.JPG)

**Comment by narongchaip** [comment]
release 2.0.7.0 is same.

**Comment by hemantbansal** [comment]
Solved in release 2.1.3.0

**Comment by narongchaip** [comment]
Thank You for Solved.
