### ISSUE TITLE
Cannot edit Packing List Number (Release 2.1.2.3)

### ISSUE THREAD

**Issue by narongchaip** [tggwlcube/CuBe_NTS#11]
In Release 2.1.2.3 
cannot edit packing list number
textbox disabled.

![cube_nts_issue_05022015_01](https://cloud.githubusercontent.com/assets/9858029/6053792/cb214f38-ad16-11e4-92ae-3716f857d25d.JPG)

**Comment by hemantbansal** [comment]
Solved in Release 2.1.2.3, Please check
