### ISSUE TITLE
Sometime, Cannot Add new Project. [Release 2.1.3.1 & 2.1.3.2]

### ISSUE THREAD

**Issue by narongchaip** [tggwlcube/CuBe_NTS#14]
Cannot add new project, but sometime can.

![cube_nts_issue_17032015_01](https://cloud.githubusercontent.com/assets/9858029/6681180/c365518e-cc94-11e4-971a-95b1b5d68a40.JPG)

**Comment by hemantbansal** [comment]
It is solved in Release 2.1.3.3

**Comment by narongchaip** [comment]
Thank You.
