### ISSUE TITLE
Small text and thin line in shape image 

### ISSUE THREAD

**Issue by narongchaip** [tggwlcube/CuBe_NTS#4]
In Release 2.0.8.0
    - small text in shape image
    - thin line of shape image
![cube_issue_02](https://cloud.githubusercontent.com/assets/9858029/5483060/a116d4e0-869e-11e4-86f0-303ec9e4f1e4.JPG)
![cube_issue_03](https://cloud.githubusercontent.com/assets/9858029/5483061/a11a9a12-869e-11e4-835e-a90200553d13.JPG)
![cube_issue_04](https://cloud.githubusercontent.com/assets/9858029/5483063/a11eddb6-869e-11e4-8c85-4456514e98ca.JPG)
![cube_issue_05](https://cloud.githubusercontent.com/assets/9858029/5483062/a11ac24e-869e-11e4-8b27-637445f11a7d.JPG)

Figure 1,3 and 4 , from Release 2.0.8.0
Figure 2 , from Release 2.0.7.0

  When I edit item in ITEM Detail window have big text and think line , then I click save button shape image change to small text and thin line. 
  As a result, when print tag cannot read text of shape.

Best Regard.

**Comment by hemantbansal** [comment]
Hi Narong Chai, I want to know as following
1. Do you want Big Text and thick line BBS detail form or Tag Detail Form.
2. Or you are concerned only about shape image quality in Tag page.

**Comment by narongchaip** [comment]
Khun Apichat and operator said it's small text and thin line, want original in old release (2.0.7.0 not sure) because when use tag print, shape image isn't clear. original better than new release.

**Comment by hemantbansal** [comment]
HI Khun Narong Chai, Please add Shape Id 5BN012 in any temporary order and then take the tag print on actual tag from Plan report menu, then please let us see the shape quality on actual tag, 
You can do this in NTS Test Database
