### ISSUE TITLE
Cannot edit length

### ISSUE THREAD

**Issue by narongchaip** [tggwlcube/CuBe_NTS#5]
Date Time Stamp : 12-Jan-2015 11:03:16
Source of error :    at System.Data.OleDb.OleDbCommand.ExecuteReaderInternal(CommandBehavior behavior, String method)
   at System.Data.OleDb.OleDbCommand.ExecuteNonQuery()
   at CuBe.t_tool.updatequery_img(String strupdate)
Error Details : The statement has been terminated.
The UPDATE statement conflicted with the FOREIGN KEY constraint "FK_T_CAB_ITEM_DTLS_T_CAB_SHAPE_MAST". The conflict occurred in database "Cube_New", table "dbo.T_CAB_SHAPE_MAST", column 'CSM_SHAPE_ID'.

---

Date Time Stamp : 12-Jan-2015 11:16:23
Source of error :    at System.Data.OleDb.OleDbCommand.ExecuteReaderInternal(CommandBehavior behavior, String method)
   at System.Data.OleDb.OleDbCommand.ExecuteNonQuery()
   at CuBe.t_tool.updatequery_img(String strupdate)
Error Details : The statement has been terminated.
The UPDATE statement conflicted with the FOREIGN KEY constraint "FK_T_CAB_ITEM_DTLS_T_CAB_SHAPE_MAST". The conflict occurred in database "Cube_New", table "dbo.T_CAB_SHAPE_MAST", column 'CSM_SHAPE_ID'.

---

Date Time Stamp : 12-Jan-2015 11:17:02
Source of error :    at System.Data.OleDb.OleDbCommand.ExecuteReaderInternal(CommandBehavior behavior, String method)
   at System.Data.OleDb.OleDbCommand.ExecuteNonQuery()
   at CuBe.t_tool.updatequery_img(String strupdate)
Error Details : The statement has been terminated.
The UPDATE statement conflicted with the FOREIGN KEY constraint "FK_T_CAB_ITEM_DTLS_T_CAB_SHAPE_MAST". The conflict occurred in database "Cube_New", table "dbo.T_CAB_SHAPE_MAST", column 'CSM_SHAPE_ID'.

---

Date Time Stamp : 12-Jan-2015 11:18:43
Source of error :    at System.Data.OleDb.OleDbCommand.ExecuteReaderInternal(CommandBehavior behavior, String method)
   at System.Data.OleDb.OleDbCommand.ExecuteNonQuery()
   at CuBe.t_tool.updatequery_img(String strupdate)
Error Details : The statement has been terminated.
The UPDATE statement conflicted with the FOREIGN KEY constraint "FK_T_CAB_ITEM_DTLS_T_CAB_SHAPE_MAST". The conflict occurred in database "Cube_New", table "dbo.T_CAB_SHAPE_MAST", column 'CSM_SHAPE_ID'.

---

Date Time Stamp : 12-Jan-2015 11:19:18
Source of error :    at System.Data.OleDb.OleDbCommand.ExecuteReaderInternal(CommandBehavior behavior, String method)
   at System.Data.OleDb.OleDbCommand.ExecuteNonQuery()
   at CuBe.t_tool.updatequery_img(String strupdate)
Error Details : The statement has been terminated.
The UPDATE statement conflicted with the FOREIGN KEY constraint "FK_T_CAB_ITEM_DTLS_T_CAB_SHAPE_MAST". The conflict occurred in database "Cube_New", table "dbo.T_CAB_SHAPE_MAST", column 'CSM_SHAPE_ID'.

---

Date Time Stamp : 12-Jan-2015 11:20:16
Source of error :    at System.Data.OleDb.OleDbCommand.ExecuteReaderInternal(CommandBehavior behavior, String method)
   at System.Data.OleDb.OleDbCommand.ExecuteNonQuery()
   at CuBe.t_tool.updatequery_img(String strupdate)
Error Details : The statement has been terminated.
The UPDATE statement conflicted with the FOREIGN KEY constraint "FK_T_CAB_ITEM_DTLS_T_CAB_SHAPE_MAST". The conflict occurred in database "Cube_New", table "dbo.T_CAB_SHAPE_MAST", column 'CSM_SHAPE_ID'.

---

Date Time Stamp : 12-Jan-2015 11:21:26
Source of error :    at System.Data.OleDb.OleDbCommand.ExecuteReaderInternal(CommandBehavior behavior, String method)
   at System.Data.OleDb.OleDbCommand.ExecuteNonQuery()
   at CuBe.t_tool.updatequery_img(String strupdate)
Error Details : The statement has been terminated.
The UPDATE statement conflicted with the FOREIGN KEY constraint "FK_T_CAB_ITEM_DTLS_T_CAB_SHAPE_MAST". The conflict occurred in database "Cube_New", table "dbo.T_CAB_SHAPE_MAST", column 'CSM_SHAPE_ID'.

---

Date Time Stamp : 12-Jan-2015 11:26:49
Source of error :    at System.Data.OleDb.OleDbCommand.ExecuteReaderInternal(CommandBehavior behavior, String method)
   at System.Data.OleDb.OleDbCommand.ExecuteNonQuery()
   at CuBe.t_tool.updatequery_img(String strupdate)
Error Details : The statement has been terminated.
The UPDATE statement conflicted with the FOREIGN KEY constraint "FK_T_CAB_ITEM_DTLS_T_CAB_SHAPE_MAST". The conflict occurred in database "Cube_New", table "dbo.T_CAB_SHAPE_MAST", column 'CSM_SHAPE_ID'.

---

Date Time Stamp : 12-Jan-2015 11:27:24
Source of error :    at System.Data.OleDb.OleDbCommand.ExecuteReaderInternal(CommandBehavior behavior, String method)
   at System.Data.OleDb.OleDbCommand.ExecuteNonQuery()
   at CuBe.t_tool.updatequery_img(String strupdate)
Error Details : The statement has been terminated.
The UPDATE statement conflicted with the FOREIGN KEY constraint "FK_T_CAB_ITEM_DTLS_T_CAB_SHAPE_MAST". The conflict occurred in database "Cube_New", table "dbo.T_CAB_SHAPE_MAST", column 'CSM_SHAPE_ID'.

---

Date Time Stamp : 12-Jan-2015 11:29:24
Source of error :    at System.Data.OleDb.OleDbCommand.ExecuteReaderInternal(CommandBehavior behavior, String method)
   at System.Data.OleDb.OleDbCommand.ExecuteNonQuery()
   at CuBe.t_tool.updatequery_img(String strupdate)
Error Details : The statement has been terminated.
The UPDATE statement conflicted with the FOREIGN KEY constraint "FK_T_CAB_ITEM_DTLS_T_CAB_SHAPE_MAST". The conflict occurred in database "Cube_New", table "dbo.T_CAB_SHAPE_MAST", column 'CSM_SHAPE_ID'.

---

Date Time Stamp : 12-Jan-2015 11:33:22
Source of error :    at System.Data.OleDb.OleDbCommand.ExecuteReaderInternal(CommandBehavior behavior, String method)
   at System.Data.OleDb.OleDbCommand.ExecuteNonQuery()
   at CuBe.t_tool.updatequery_img(String strupdate)
Error Details : The statement has been terminated.
The UPDATE statement conflicted with the FOREIGN KEY constraint "FK_T_CAB_ITEM_DTLS_T_CAB_SHAPE_MAST". The conflict occurred in database "Cube_New", table "dbo.T_CAB_SHAPE_MAST", column 'CSM_SHAPE_ID'.

---

**Comment by narongchaip** [comment]
![cube_issue_120212014_01](https://cloud.githubusercontent.com/assets/9858029/5699067/adebafd6-9a50-11e4-865a-6dac3bfe4d8a.JPG)
![cube_issue_120212014_02](https://cloud.githubusercontent.com/assets/9858029/5699069/adefa6f4-9a50-11e4-823e-ccec391e75b1.JPG)
![capture](https://cloud.githubusercontent.com/assets/9858029/5699066/adeb0f72-9a50-11e4-8dc0-f34257e2c9f2.JPG)
![cube_issue_120212014_04](https://cloud.githubusercontent.com/assets/9858029/5699068/adee7b80-9a50-11e4-875b-3b35ea988023.JPG)

**Comment by narongchaip** [comment]
want to edit length 28 but image show 280

**Comment by narongchaip** [comment]
in Release 2.1.0.0 cannot edit item.

**Comment by hemantbansal** [comment]
Issue is solved in release no. 2.1.1.0, Please test

**Comment by narongchaip** [comment]
Now, can edit tag.
Thank you for support.
