### ISSUE TITLE
In CAB BBS Detail window of Release 2.1.1.0 not show some shape but show in Release 2.0.7.0

### ISSUE THREAD

**Issue by narongchaip** [tggwlcube/CuBe_NTS#6]
Packinglist CB1501-082 have L shapes and 1 U shape
release 2.0.7.0 show all shapes but 2.1.1.0 show U shape only. 
![cube_nts_issue_15012015_01](https://cloud.githubusercontent.com/assets/9858029/5753475/ae035ec4-9cbc-11e4-9194-b92e0149abfb.JPG)
![cube_nts_issue_15012015_02](https://cloud.githubusercontent.com/assets/9858029/5753479/b65b6580-9cbc-11e4-8902-43e4aa351026.JPG)

Packinglist CB1501-084 have 1 straight line shape 
release 2.0.7.0 can show shape but 2.1.1.0 not show. 
![cube_nts_issue_15012015_03](https://cloud.githubusercontent.com/assets/9858029/5753477/b62c09de-9cbc-11e4-8ccc-107f234d73cc.JPG)
![cube_nts_issue_15012015_04](https://cloud.githubusercontent.com/assets/9858029/5753478/b65a434e-9cbc-11e4-9232-e7f9be21164a.JPG)

**Comment by narongchaip** [comment]
If create new item in Release 2.1.1.0 (straight line shape). 
can show that item in 2.0.7.0

**Comment by hemantbansal** [comment]
1. I will correct this issue for now temporary.
2. Please use only latest release for Order Entry, like Release 2.1.1.0, 
3. As Shape mapping Feature is implemented. Please use only new Shape Ids.
4. For Straight Length New Shape Id is 0BN001

**Comment by hemantbansal** [comment]
Solved, Please check now

**Comment by narongchaip** [comment]
Now, Items already shown.
Thank you for Support.

**Comment by narongchaip** [comment]
Packing list CB1501-026 have Coupler items
release 2.0.7.0 show all items but release 2.1.1.0 not show.

![cube_nts_issue_20012015_01](https://cloud.githubusercontent.com/assets/9858029/5811590/bd20e3fe-a08b-11e4-8259-b46f5672b3e5.JPG)

![cube_nts_issue_20012015_02](https://cloud.githubusercontent.com/assets/9858029/5811585/af41f0c0-a08b-11e4-89f0-24f20f53c72d.JPG)

**Comment by hemantbansal** [comment]
Solved in Release 2.1.2.3 , Please check

**Comment by narongchaip** [comment]
Thank You.
