### ISSUE TITLE
Cannot edit DeliveryAddress in PackingList Detail (Release 2.1.1.0)

### ISSUE THREAD

**Issue by narongchaip** [tggwlcube/CuBe_NTS#8]
![cube_nts_issue_29012015_01](https://cloud.githubusercontent.com/assets/9858029/5951658/a1777484-a79c-11e4-8e36-163615ea7531.JPG)
![cube_nts_issue_29012015_02](https://cloud.githubusercontent.com/assets/9858029/5951659/a179c0ea-a79c-11e4-9682-160909e94c3a.JPG)

**Comment by hemantbansal** [comment]
Solved in Release 2.1.2.3, Please check

**Comment by narongchaip** [comment]
Thank You.
