### ISSUE TITLE
Cannot edit shape in CABShape window (change type : normal --> actual for delete offse ) in Release 2.1.1.0

### ISSUE THREAD

**Issue by narongchaip** [tggwlcube/CuBe_NTS#9]
![cube_nts_issue_04022015_01](https://cloud.githubusercontent.com/assets/9858029/6034691/7c04bfac-ac58-11e4-82fd-4b7e6cbf8448.JPG)
![cube_nts_issue_04022015_02](https://cloud.githubusercontent.com/assets/9858029/6034692/7c087250-ac58-11e4-83d6-dae116fe629a.JPG)
![cube_nts_issue_04022015_03](https://cloud.githubusercontent.com/assets/9858029/6034694/7c099bee-ac58-11e4-8f1c-01b851c16bbe.JPG)
![cube_nts_issue_04022015_04](https://cloud.githubusercontent.com/assets/9858029/6034693/7c094270-ac58-11e4-8ed8-eb5e97b6520e.JPG)

**Comment by hemantbansal** [comment]
Solved in Release no. 2.1.2.3, Please check

**Comment by narongchaip** [comment]
Thank You.
